In [1]:
import numpy as np

In [2]:
x = np.random.randn(4,5)

In [3]:
x

array([[-0.63438108,  0.09292499,  0.47685818, -0.69749924,  0.07226992],
       [-0.02313996, -0.16502646,  1.47988696,  0.86189732, -1.75264167],
       [-0.08669265, -1.45733331, -1.6609634 , -1.02672275,  1.08544637],
       [-1.27920976, -2.06617154,  0.5428713 , -0.58423753,  2.61992657]])

In [4]:
x.reshape(2,2,5) # By Default python uses C order

array([[[-0.63438108,  0.09292499,  0.47685818, -0.69749924,
          0.07226992],
        [-0.02313996, -0.16502646,  1.47988696,  0.86189732,
         -1.75264167]],

       [[-0.08669265, -1.45733331, -1.6609634 , -1.02672275,
          1.08544637],
        [-1.27920976, -2.06617154,  0.5428713 , -0.58423753,
          2.61992657]]])

In [5]:
x.reshape((2,2,5),order = "F") #Fortran Order 

array([[[-0.63438108,  0.09292499,  0.47685818, -0.69749924,
          0.07226992],
        [-0.08669265, -1.45733331, -1.6609634 , -1.02672275,
          1.08544637]],

       [[-0.02313996, -0.16502646,  1.47988696,  0.86189732,
         -1.75264167],
        [-1.27920976, -2.06617154,  0.5428713 , -0.58423753,
          2.61992657]]])

In [6]:
x.reshape((2,2,-1)) # -1 Skips the data from the dimension and is responsible for the data of that dimension 

array([[[-0.63438108,  0.09292499,  0.47685818, -0.69749924,
          0.07226992],
        [-0.02313996, -0.16502646,  1.47988696,  0.86189732,
         -1.75264167]],

       [[-0.08669265, -1.45733331, -1.6609634 , -1.02672275,
          1.08544637],
        [-1.27920976, -2.06617154,  0.5428713 , -0.58423753,
          2.61992657]]])

In [7]:
x

array([[-0.63438108,  0.09292499,  0.47685818, -0.69749924,  0.07226992],
       [-0.02313996, -0.16502646,  1.47988696,  0.86189732, -1.75264167],
       [-0.08669265, -1.45733331, -1.6609634 , -1.02672275,  1.08544637],
       [-1.27920976, -2.06617154,  0.5428713 , -0.58423753,  2.61992657]])

In [8]:
x.ravel()

array([-0.63438108,  0.09292499,  0.47685818, -0.69749924,  0.07226992,
       -0.02313996, -0.16502646,  1.47988696,  0.86189732, -1.75264167,
       -0.08669265, -1.45733331, -1.6609634 , -1.02672275,  1.08544637,
       -1.27920976, -2.06617154,  0.5428713 , -0.58423753,  2.61992657])

In [9]:
x.flatten()

array([-0.63438108,  0.09292499,  0.47685818, -0.69749924,  0.07226992,
       -0.02313996, -0.16502646,  1.47988696,  0.86189732, -1.75264167,
       -0.08669265, -1.45733331, -1.6609634 , -1.02672275,  1.08544637,
       -1.27920976, -2.06617154,  0.5428713 , -0.58423753,  2.61992657])