In [1]:
import numpy as np

In [2]:
x = np.array([1,7,9,8,5])

In [3]:
x[4] #Indexing

5

In [4]:
x[x>5] #Boolean Indexing

array([7, 9, 8])

In [5]:
x[[2,1]] # Fancy Indexing.

array([9, 7])

In [7]:
x = np.random.randn(10,10)

In [8]:
x

array([[ 1.16476842,  0.76453203, -0.93057441, -1.50883894, -1.31700304,
        -1.89742319, -0.09819352,  0.52848987,  2.05296746, -0.33698885],
       [-1.3814185 ,  0.71497404,  1.10972922, -1.1194793 ,  0.39491186,
         1.15421456,  0.78227436,  0.27126316, -0.37820133,  0.90584712],
       [ 2.28055918, -1.09982949, -0.09976515,  1.28861532, -0.07083922,
        -2.57390133, -0.60674811, -0.49469496, -0.55196474,  0.48152438],
       [-0.65940185,  0.4364308 , -0.99267854, -1.00478045,  0.71726396,
        -0.15791935,  1.61074845,  0.05701596,  0.3642187 ,  0.11374587],
       [ 0.15358211, -0.53742681,  0.21174111,  1.11996821, -0.88041727,
        -0.23925089,  0.77058999,  0.04139627, -1.48622271, -0.63956494],
       [-1.33140962, -1.15547736,  0.14816919,  0.39090216, -1.19629693,
         0.06955261, -1.5185307 ,  1.28265409,  1.86201074,  0.30815817],
       [ 1.39480091, -0.84266499, -0.20128275,  0.35475196, -0.89916846,
         0.67401001,  2.25574662, -0.31099344

In [9]:
x[0]

array([ 1.16476842,  0.76453203, -0.93057441, -1.50883894, -1.31700304,
       -1.89742319, -0.09819352,  0.52848987,  2.05296746, -0.33698885])

In [10]:
x[0][4]

-1.317003043313233

In [12]:
x[1:10:2]

array([[-1.3814185 ,  0.71497404,  1.10972922, -1.1194793 ,  0.39491186,
         1.15421456,  0.78227436,  0.27126316, -0.37820133,  0.90584712],
       [-0.65940185,  0.4364308 , -0.99267854, -1.00478045,  0.71726396,
        -0.15791935,  1.61074845,  0.05701596,  0.3642187 ,  0.11374587],
       [-1.33140962, -1.15547736,  0.14816919,  0.39090216, -1.19629693,
         0.06955261, -1.5185307 ,  1.28265409,  1.86201074,  0.30815817],
       [ 0.26869159, -1.44382457,  0.33460136, -0.25192035, -1.84095399,
        -2.18323061, -0.00271479,  0.57529928,  0.76899259, -0.74402969],
       [ 0.64036475, -1.42582309,  0.20064955, -1.19998377,  0.67482325,
        -1.0410289 , -0.40710179,  0.52049869,  1.65455577,  0.23322194]])

In [13]:
x[::,0:4]

array([[ 1.16476842,  0.76453203, -0.93057441, -1.50883894],
       [-1.3814185 ,  0.71497404,  1.10972922, -1.1194793 ],
       [ 2.28055918, -1.09982949, -0.09976515,  1.28861532],
       [-0.65940185,  0.4364308 , -0.99267854, -1.00478045],
       [ 0.15358211, -0.53742681,  0.21174111,  1.11996821],
       [-1.33140962, -1.15547736,  0.14816919,  0.39090216],
       [ 1.39480091, -0.84266499, -0.20128275,  0.35475196],
       [ 0.26869159, -1.44382457,  0.33460136, -0.25192035],
       [-0.24180429,  1.22585077,  2.43115618, -1.41853272],
       [ 0.64036475, -1.42582309,  0.20064955, -1.19998377]])

In [24]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
x[1:-1,1:-1]=0

In [26]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])